- default sum_load flipped to True for testing  - removing python 3.6 testing because of:
======================================================================
ERROR: test_stress (pyNastran.op2.test.examples.test_op2_in_material_coord.TestMaterialCoord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SteveDoyle2/pyNastran/pyNastran/op2/test/examples/test_op2_in_material_coord.py", line 59, in test_stress
    op2_new = data_in_material_coord(bdf, op2)
  File "/home/travis/build/SteveDoyle2/pyNastran/pyNastran/op2/data_in_material_coord.py", line 175, in data_in_material_coord
    op2_new = copy.deepcopy(op2)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle Struct objects